$(document).ready(function(){
  $("#picOne").click(function(){
    $("#unitedNations").toggle();
    $("#picOne").hide();
  $("#unitedNations").click(function(){
    $("#picOne").show();
    $("#unitedNations").hide();
    });
  });
});
$(document).ready(function(){
  $("#picTwo").click(function(){
    $("#microsoftTech").toggle();
    $("#picTwo").hide();
  $("#microsoftTech").click(function(){
    $("#picTwo").show();
    $("#microsoftTech").hide();
    });
  });
});
$(document).ready(function(){
  $("#picThree").click(function(){
    $("#googleTech").toggle();
    $("#picThree").hide();
  $("#googleTech").click(function(){
    $("#picThree").show();
    $("#googleTech").hide();
    });
  });
});
$(document).ready(function(){
  $("#picFour").click(function(){
    $("#kenyaAirways").toggle();
    $("#picFour").hide();
  $("#kenyaAirways").click(function(){
    $("#picFour").show();
    $("#kenyaAirways").hide();
    });
  });
});
$(document).ready(function(){
  $("#picEleven").click(function(){
    $("#amazon").toggle();
    $("#picEleven").hide();
  $("#amazon").click(function(){
    $("#picEleven").show();
    $("#amazon").hide();
    });
  });
});
$(document).ready(function(){
  $("#picTwelve").click(function(){
    $("#eabl").toggle();
    $("#picTwelve").hide();
  $("#eabl").click(function(){
    $("#picTwelve").show();
    $("#eabl").hide();
    });
  });
});
$(document).ready(function(){
  $("#picThirteen").click(function(){
    $("#standard").toggle();
    $("#picThirteen").hide();
  $("#standard").click(function(){
    $("#picThirteen").show();
    $("#standard").hide();
    });
  });
});
$(document).ready(function(){
  $("#picFourteen").click(function(){
    $("#opportunities").toggle();
    $("#picFourteen").hide();
  $("#opportunities").click(function(){
    $("#picFourteen").show();
    $("#opportunities").hide();
    });
  });
});
$(document).ready(function(){
  $("#picFifteen").click(function(){
    $("#impact").toggle();
    $("#picFifteen").hide();
  $("#impact").click(function(){
    $("#picFifteen").show();
    $("#impact").hide();
    });
  });
});